{% set name = "django-compressor" %}
{% set version = "4.5" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/django_compressor-{{ version }}.tar.gz
  sha256: 9d98c905b741be6cb09ad828c1d22a9ff9244dd08823e2926af8ddd1871c3c65

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.8
    - pip
  run:
    - python >=3.8
    - django-appconf >=1.0.3
    - rcssmin ==1.1.1
    - rjsmin ==1.2.1

test:
  imports:
    - compressor
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/django-compressor/django-compressor
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: 'Compresses linked and inline javascript or CSS into a single cached file.'
  description: Django Compressor processes, combines and minifies linked and inline Javascript or CSS in a Django template into cacheable static files. It supports compilers such as coffeescript, LESS and SASS and is extensible by custom processing steps. Django Compressor is compatible with Django 1.8 and newer.
  doc_url: https://django-compressor.readthedocs.io/en/latest/
  dev_url: https://github.com/django-compressor/django-compressor

extra:
  recipe-maintainers:
    - cshaley
    - sannykr
    - rxm7706
