{% set name = "django-compressor" %}
{% set version = "4.5.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/django_compressor-{{ version }}.tar.gz
  sha256: c1d8a48a2ee4d8b7f23c411eb9c97e2d88db18a18ba1c9e8178d5f5b8366a822

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.8
    - pip
  run:
    - python >=3.8
    - django >=4.2
    - django-appconf >=1.0.3
    - rcssmin ==1.1.2
    - rjsmin ==1.2.2

test:
  imports:
    - compressor
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/django-compressor/django-compressor
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: 'Compresses linked and inline javascript or CSS into a single cached file.'
  description: Django Compressor processes, combines and minifies linked and inline Javascript or CSS in a Django template into cacheable static files. It supports compilers such as coffeescript, LESS and SASS and is extensible by custom processing steps. Django Compressor is compatible with Django 1.8 and newer.
  doc_url: https://django-compressor.readthedocs.io/en/latest/
  dev_url: https://github.com/django-compressor/django-compressor

extra:
  recipe-maintainers:
    - cshaley
    - sannykr
    - rxm7706
