{% set name = "django_compressor" %}
{% set version = "3.0" %}
{% set sha256 = "68955b7baffc3607a4dc44523dcff622238121b307f46fecddaeb8de986ca086" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  host:
    - pip
    - python
    - setuptools
  run:
    - python
    - django >=1.8
    - django-appconf >=1.0
    - rcssmin ==1.0.6
    - rjsmin ==1.0.12

about:
  home: https://github.com/django-compressor/django-compressor
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: Compresses linked and inline javascript or CSS into a single cached file.
  description: Django Compressor processes, combines and minifies linked and inline Javascript or CSS in a Django template into cacheable static files. It supports compilers such as coffeescript, LESS and SASS and is extensible by custom processing steps. Django Compressor is compatible with Django 1.8 and newer.
  doc_url: https://django-compressor.readthedocs.io/en/latest/
  dev_url: https://github.com/django-compressor/django-compressor

extra:
  recipe-maintainers:
    - cshaley
    - sannykr
